$ANSIBLE_VAULT;1.1;AES256
64303030353336663132333061353562333534633564626665353534356266653037383339666466
3330313639663033383434653934306332366231626231360a336362376164383230366632366163
34313039616639376139636539303231386632353262643439393537366638366562383563313635
3831393462366533390a373137393933633538636639363233613266393261646162373337616665
66613235363864363032353730663736663964636435346236626261643731653235653333383739
36373665616338363237613837356231313234343339333166356664393237666264623134623738
34633338636666333633343766383263636532393365643064303165633938623166326137376466
65323937663564323630346435643365613463653331633138616666326164376166613562663937
33306161326631616262313337313664626166363331333835643232663433313937363734346234
63373639373233626264653338366233653439373736313362343133386566313639356638616663
33383136616532306135393132303363623238633439333464366633383734383936633137646630
38636437633435643466663835623061386362666531306564396366666337346161663131303161
3230
